In [39]:
import os
import pandas as pd
import numpy as np

In [40]:
# Read data from CSV files
happiness_19_df = pd.read_csv(os.path.join('C:/Users/roelj/OneDrive/Desktop/school/Project-3/csv/happy_2019.csv'))
happiness_20_df = pd.read_csv(os.path.join('C:/Users/roelj/OneDrive/Desktop/school/Project-3/csv/happy_2020.csv'))
happiness_21_df = pd.read_csv(os.path.join(r'C:\Users\roelj\OneDrive\Desktop\school\Project-3\csv\happy_2021.csv'))

In [41]:
happiness_19_df.sort_values(by=['countries']).head()

,countries,HappinessRank,HappinessScore,GDP_per_capita,SocialSupport,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
153,Afghanistan,154,3.20,0.35,0.52,0.36,0.00,0.16,0.03
106,Albania,107,4.72,0.95,0.85,0.87,0.38,0.18,0.03
87,Algeria,88,5.21,1.00,1.16,0.79,0.09,0.07,0.11
46,Argentina,47,6.09,1.09,1.43,0.88,0.47,0.07,0.05
115,Armenia,116,4.56,0.85,1.06,0.82,0.28,0.10,0.06

In [42]:
happiness_20_df.sort_values(by=['Country name']).head()

,Country name,HappinessRank,HappinessScore,GDP_per_capita,SocialSupport,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
152,Afghanistan,153,2.5669,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687
104,Albania,105,4.8827,9.417931,0.671070,68.708138,0.781994,-0.042309,0.896304
99,Algeria,100,5.0051,9.537965,0.803385,65.905174,0.466611,-0.121105,0.735485
54,Argentina,55,5.9747,9.810955,0.900568,68.803802,0.831132,-0.194914,0.842010
115,Armenia,116,4.6768,9.100476,0.757479,66.750656,0.712018,-0.138780,0.773545

In [43]:
happiness_21_df.sort_values(by=['Country name']).head()

,Country name,HappinessRank,HappinesScore,GDP_per _capita,SocialSupport,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
148,Afghanistan,149,2.523,7.695,0.463,52.493,0.382,-0.102,0.924
92,Albania,93,5.117,9.520,0.697,68.999,0.785,-0.030,0.901
108,Algeria,109,4.887,9.342,0.802,66.005,0.480,-0.067,0.752
56,Argentina,57,5.929,9.962,0.898,69.000,0.828,-0.182,0.834
85,Armenia,86,5.283,9.487,0.799,67.055,0.825,-0.168,0.629

In [44]:
list_2019 = []
for countries in happiness_19_df['countries']:
    list_2019.append(countries)
list_2020 = []
for Country  in happiness_20_df['Country name']:
    list_2020.append('Country name')
list_2021 = []
for country in happiness_21_df['Country name']:
    list_2021.append('Country name')

In [45]:
print(list_2019)
print(list_2020)
print(list_2021)

['Finland', 'Denmark', 'Norway', 'Iceland', 'Netherlands', 'Switzerland', 'Sweden', 'New Zealand', 'Canada', 'Austria', 'Australia', 'Costa Rica', 'Israel', 'Luxembourg', 'United Kingdom', 'Ireland', 'Germany', 'Belgium', 'United States', 'Czech Republic', 'United Arab Emirates', 'Malta', 'Mexico', 'France', 'Taiwan', 'Chile', 'Guatemala', 'Saudi Arabia', 'Qatar', 'Spain', 'Panama', 'Brazil', 'Uruguay', 'Singapore', 'El Salvador', 'Italy', 'Bahrain', 'Slovakia', 'Trinidad & Tobago', 'Poland', 'Uzbekistan', 'Lithuania', 'Colombia', 'Slovenia', 'Nicaragua', 'Kosovo', 'Argentina', 'Romania', 'Cyprus', 'Ecuador', 'Kuwait', 'Thailand', 'Latvia', 'South Korea', 'Estonia', 'Jamaica', 'Mauritius', 'Japan', 'Honduras', 'Kazakhstan', 'Bolivia', 'Hungary', 'Paraguay', 'Northern Cyprus', 'Peru', 'Portugal', 'Pakistan', 'Russia', 'Philippines', 'Serbia', 'Moldova', 'Libya', 'Montenegro', 'Tajikistan', 'Croatia', 'Hong Kong', 'Dominican Republic', 'Bosnia and Herzegovina', 'Turkey', 'Malaysia', 'Belarus', 'Greece', 'Mongolia', 'North Macedonia', 'Nigeria', 'Kyrgyzstan', 'Turkmenistan', 'Algeria', 'Morocco', 'Azerbaijan', 'Lebanon', 'Indonesia', 'China', 'Vietnam', 'Bhutan', 'Cameroon', 'Bulgaria', 'Ghana', 'Ivory Coast', 'Nepal', 'Jordan', 'Benin', 'Congo (Brazzaville)', 'Gabon', 'Laos', 'South Africa', 'Albania', 'Venezuela', 'Cambodia', 'Palestinian Territories', 'Senegal', 'Somalia', 'Namibia', 'Niger', 'Burkina Faso', 'Armenia', 'Iran', 'Guinea', 'Georgia', 'Gambia', 'Kenya', 'Mauritania', 'Mozambique', 'Tunisia', 'Bangladesh', 'Iraq', 'Congo (Kinshasa)', 'Mali', 'Sierra Leone', 'Sri Lanka', 'Myanmar', 'Chad', 'Ukraine', 'Ethiopia', 'Swaziland', 'Uganda', 'Egypt', 'Zambia', 'Togo', 'India', 'Liberia', 'Comoros', 'Madagascar', 'Lesotho', 'Burundi', 'Zimbabwe', 'Haiti', 'Botswana', 'Syria', 'Malawi', 'Yemen', 'Rwanda', 'Tanzania', 'Afghanistan', 'Central African Republic', 'South Sudan']
['Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name']
['Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name', 'Country name']

In [46]:
country_list = []
def list_country(l):
    for country in l:
        if country in country_list:
            continue
        else:
            country_list.append(country)

In [47]:
list_country(list_2019)
list_country(list_2020)
list_country(list_2021)

country_list.sort()

In [48]:
country_list

['Afghanistan',
 'Albania',
 'Algeria',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Costa Rica',
 'Country name',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Northern Cyprus',
 'Norway',
 'Pakistan',
 'Palestinian Territories',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad & Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [49]:
country_id = []
counter = 1
for country in country_list:
    country_id.append(counter)
    counter += 1

In [50]:
country_data = {'country':country_list, 'country_id':country_id}

country_data

{'country': ['Afghanistan',
  'Albania',
  'Algeria',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Country name',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Guinea',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Northern Cyprus',
  'Norway',
  'Pakistan',
  'Palestinian Territories',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'],
 'country_id': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157]}

In [52]:
country_df = pd.DataFrame.from_dict(country_data)

country_df = pd.read_csv(os.path.join(r'C:\Users\roelj\OneDrive\Desktop\school\Project-3\csv\countries.csv'))

In [53]:
country_id_dict = dict()
for index,row in country_df.iterrows() :
    country_name = row['country']
    country_id = row['country_id']
    country_id_dict[country_name] = country_id

In [54]:
country_id_dict

{'Afghanistan': 1,
 'Albania': 2,
 'Algeria': 3,
 'Angola': 4,
 'Argentina': 5,
 'Armenia': 6,
 'Australia': 7,
 'Austria': 8,
 'Azerbaijan': 9,
 'Bahrain': 10,
 'Bangladesh': 11,
 'Belarus': 12,
 'Belgium': 13,
 'Belize': 14,
 'Benin': 15,
 'Bhutan': 16,
 'Bolivia': 17,
 'Bosnia and Herzegovina': 18,
 'Botswana': 19,
 'Brazil': 20,
 'Bulgaria': 21,
 'Burkina Faso': 22,
 'Burundi': 23,
 'Cambodia': 24,
 'Cameroon': 25,
 'Canada': 26,
 'Central African Republic': 27,
 'Chad': 28,
 'Chile': 29,
 'China': 30,
 'Colombia': 31,
 'Comoros': 32,
 'Congo (Brazzaville)': 33,
 'Congo (Kinshasa)': 34,
 'Costa Rica': 35,
 'Croatia': 36,
 'Cyprus': 37,
 'Czech Republic': 38,
 'Denmark': 39,
 'Djibouti': 40,
 'Dominican Republic': 41,
 'Ecuador': 42,
 'Egypt': 43,
 'El Salvador': 44,
 'Estonia': 45,
 'Ethiopia': 46,
 'Finland': 47,
 'France': 48,
 'Gabon': 49,
 'Georgia': 50,
 'Germany': 51,
 'Ghana': 52,
 'Greece': 53,
 'Guatemala': 54,
 'Guinea': 55,
 'Haiti': 56,
 'Honduras': 57,
 'Hong Kong': 58,
 'Hong Kong S.A.R., China': 59,
 'Hungary': 60,
 'Iceland': 61,
 'India': 62,
 'Indonesia': 63,
 'Iran': 64,
 'Iraq': 65,
 'Ireland': 66,
 'Israel': 67,
 'Italy': 68,
 'Ivory Coast': 69,
 'Jamaica': 70,
 'Japan': 71,
 'Jordan': 72,
 'Kazakhstan': 73,
 'Kenya': 74,
 'Kosovo': 75,
 'Kuwait': 76,
 'Kyrgyzstan': 77,
 'Laos': 78,
 'Latvia': 79,
 'Lebanon': 80,
 'Lesotho': 81,
 'Liberia': 82,
 'Libya': 83,
 'Lithuania': 84,
 'Luxembourg': 85,
 'Macedonia': 86,
 'Madagascar': 87,
 'Malawi': 88,
 'Malaysia': 89,
 'Mali': 90,
 'Malta': 91,
 'Mauritania': 92,
 'Mauritius': 93,
 'Mexico': 94,
 'Moldova': 95,
 'Mongolia': 96,
 'Montenegro': 97,
 'Morocco': 98,
 'Mozambique': 99,
 'Myanmar': 100,
 'Namibia': 101,
 'Nepal': 102,
 'Netherlands': 103,
 'New Zealand': 104,
 'Nicaragua': 105,
 'Niger': 106,
 'Nigeria': 107,
 'North Cyprus': 108,
 'Norway': 109,
 'Oman': 110,
 'Pakistan': 111,
 'Palestinian Territories': 112,
 'Panama': 113,
 'Paraguay': 114,
 'Peru': 115,
 'Philippines': 116,
 'Poland': 117,
 'Portugal': 118,
 'Puerto Rico': 119,
 'Qatar': 120,
 'Romania': 121,
 'Russia': 122,
 'Rwanda': 123,
 'Saudi Arabia': 124,
 'Senegal': 125,
 'Serbia': 126,
 'Sierra Leone': 127,
 'Singapore': 128,
 'Slovakia': 129,
 'Slovenia': 130,
 'Somalia': 131,
 'Somaliland Region': 132,
 'Somaliland region': 133,
 'South Africa': 134,
 'South Korea': 135,
 'South Sudan': 136,
 'Spain': 137,
 'Sri Lanka': 138,
 'Sudan': 139,
 'Suriname': 140,
 'Swaziland': 141,
 'Sweden': 142,
 'Switzerland': 143,
 'Syria': 144,
 'Taiwan': 145,
 'Taiwan Province of China': 146,
 'Tajikistan': 147,
 'Tanzania': 148,
 'Thailand': 149,
 'Togo': 150,
 'Trinidad and Tobago': 151,
 'Tunisia': 152,
 'Turkey': 153,
 'Turkmenistan': 154,
 'Uganda': 155,
 'Ukraine': 156,
 'United Arab Emirates': 157,
 'United Kingdom': 158,
 'United States': 159,
 'Uruguay': 160,
 'Uzbekistan': 161,
 'Venezuela': 162,
 'Vietnam': 163,
 'Yemen': 164,
 'Zambia': 165,
 'Zimbabwe': 166}

In [55]:
happiness_19_df['country_id'] =""
happiness_20_df['country_id'] =""
happiness_21_df['country_id'] =""

In [56]:
def add_country_id(df):
    for index,row in df.iterrows() :
        try:
            df.loc[index,'country_id'] = country_id_dict.get(row['Country'])
        except:
            continue

In [57]:
add_country_id(happiness_19_df)
add_country_id(happiness_20_df)
add_country_id(happiness_21_df)

In [59]:
happiness_19_df.sort_values(by=['countries'])
happiness_20_df.sort_values(by=['Country name'])
happiness_21_df.sort_values(by=['Country name'])

,Country name,HappinessRank,HappinesScore,GDP_per _capita,SocialSupport,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,country_id
148,Afghanistan,149,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,
92,Albania,93,5.117,9.520,0.697,68.999,0.785,-0.030,0.901,
108,Algeria,109,4.887,9.342,0.802,66.005,0.480,-0.067,0.752,
56,Argentina,57,5.929,9.962,0.898,69.000,0.828,-0.182,0.834,
85,Armenia,86,5.283,9.487,0.799,67.055,0.825,-0.168,0.629,
...,...,...,...,...,...,...,...,...,...,...
106,Venezuela,107,4.892,9.073,0.861,66.700,0.615,-0.169,0.827,
78,Vietnam,79,5.411,8.973,0.850,68.034,0.940,-0.098,0.796,
140,Yemen,141,3.658,7.578,0.832,57.122,0.602,-0.147,0.800,
136,Zambia,137,4.073,8.145,0.708,55.809,0.782,0.061,0.823,
147,Zimbabwe,148,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,

In [60]:
happiness_19_df = pd.read_csv(os.path.join('C:/Users/roelj/OneDrive/Desktop/school/Project-3/csv/happy_2019.csv'))
happiness_20_df = pd.read_csv(os.path.join('C:/Users/roelj/OneDrive/Desktop/school/Project-3/csv/happy_2020.csv'))
happiness_21_df = pd.read_csv(os.path.join(r'C:\Users\roelj\OneDrive\Desktop\school\Project-3\csv\happy_2021.csv'))